# Código para gerar a tabela única

## Importação das bibliotecas

In [1]:
import pandas as pd
import csv
import numpy as np
import xlrd

## Criando dataframes para todas as tabelas

In [2]:
df_end_pf = pd.read_excel('Endereço PF_NOVA.xlsx')
df_pf = pd.read_excel('PF_NOVA.xlsx')
df_mvt = pd.read_excel('MVT_NOVA.xlsx')
df_opr = pd.read_excel('OPR_NOVA.xlsx')
df_pgt = pd.read_excel('PGT_NOVA.xlsx')

## Criando a tabela que armazenará todos os dados para pesquisa

In [3]:
CONSULTA = {'cpf':[],
            'id':[],
            'idc_sexo':[],
            'ano_dat_nascimento':[],
            'nom_cidade':[],
            'des_estado':[],
            'tip_cli':[],
            'id_opr_cad_pos':[],
            'qtd_pcl':[],
            'dat_vct_ult_pcl':[],
            'vlr_ctrd_fta_tfm':[],
            'sdo_ddr_tfm':[],
            'vlr_ctrd':[],
            'cod_mdl':[],
            'id_mvt_cad_pos':[],
            'id_pgt_cad_pos':[],
            'dat_pgt':[],
            'dat_vct_tfm':[],
            'vlr_pgt_tfm':[],
            'status':[]
           }
df_consulta = pd.DataFrame(CONSULTA, columns=['cpf','id','idc_sexo','ano_dat_nascimento','nom_cidade','des_estado',
                                              'tip_cli','id_opr_cad_pos','qtd_pcl','dat_vct_ult_pcl','vlr_ctrd_fta_tfm',
                                              'sdo_ddr_tfm','vlr_ctrd','cod_mdl','id_mvt_cad_pos','id_pgt_cad_pos',
                                              'dat_pgt','dat_vct_tfm','vlr_pgt_tfm', 'status'])

In [4]:
df_consulta

Empty DataFrame
Columns: [cpf, id, idc_sexo, ano_dat_nascimento, nom_cidade, des_estado, tip_cli, id_opr_cad_pos, qtd_pcl, dat_vct_ult_pcl, vlr_ctrd_fta_tfm, sdo_ddr_tfm, vlr_ctrd, cod_mdl, id_mvt_cad_pos, id_pgt_cad_pos, dat_pgt, dat_vct_tfm, vlr_pgt_tfm, status]
Index: []

## Colocando os dados na tabela única

In [5]:
for i in df_pgt.index:
    id_opr = df_pgt.id_opr_cad_pos[i]
    df_consulta.loc[i, 'id_opr_cad_pos'] = df_pgt.loc[i, 'id_opr_cad_pos']
    df_consulta.loc[i, 'id_mvt_cad_pos'] = df_pgt.loc[i, 'id_mvt_cad_pos']
    df_consulta.loc[i, 'id_pgt_cad_pos'] = df_pgt.loc[i, 'id_pgt_cad_pos']
    df_consulta.loc[i, 'dat_pgt'] = str(df_pgt.loc[i, 'dat_pgt'])
    df_consulta.loc[i, 'dat_vct_tfm'] = df_pgt.loc[i, 'dat_vct_tfm']
    df_consulta.loc[i, 'vlr_pgt_tfm'] = df_pgt.loc[i, 'vlr_pgt_tfm']
        
    for j in df_opr.index:
        if df_opr.id_opr_cad_pos[j] == id_opr:
            cpf = df_opr.doc_cli[j]     
            df_consulta.loc[i, 'tip_cli'] = df_opr.loc[j, 'tip_cli']
            df_consulta.loc[i, 'qtd_pcl'] = df_opr.loc[j, 'qtd_pcl']
            df_consulta.loc[i, 'dat_vct_ult_pcl'] = df_opr.loc[j, 'dat_vct_ult_pcl']
            df_consulta.loc[i, 'vlr_ctrd_fta_tfm'] = df_opr.loc[j, 'vlr_ctrd_fta_tfm']
            df_consulta.loc[i, 'sdo_ddr_tfm'] = df_opr.loc[j, 'sdo_ddr_tfm']            
            df_consulta.loc[i, 'vlr_ctrd'] = df_opr.loc[j, 'vlr_ctrd']        
            df_consulta.loc[i, 'cod_mdl'] = df_opr.loc[j, 'cod_mdl']
            
            for k in df_pf.index:
                if df_pf.cpf[k] == cpf:
                    id_pf = df_pf.id[k]
                    df_consulta.loc[i, 'cpf'] = df_pf.loc[k, 'cpf']
                    df_consulta.loc[i, 'id'] = df_pf.loc[k, 'id']
                    df_consulta.loc[i, 'idc_sexo'] = df_pf.loc[k, 'idc_sexo']
                    df_consulta.loc[i, 'ano_dat_nascimento'] = df_pf.loc[k, 'ano_dat_nascimento']
                    
                    for l in df_end_pf.index:
                        if df_end_pf.id_pessoa_fisica[l] == id_pf:
                            df_consulta.loc[i, 'nom_cidade'] = df_end_pf.loc[l, 'nom_cidade']
                            df_consulta.loc[i, 'des_estado'] = df_end_pf.loc[l, 'des_estado'];

In [6]:
df_consulta

,cpf,id,idc_sexo,ano_dat_nascimento,nom_cidade,des_estado,tip_cli,id_opr_cad_pos,qtd_pcl,dat_vct_ult_pcl,vlr_ctrd_fta_tfm,sdo_ddr_tfm,vlr_ctrd,cod_mdl,id_mvt_cad_pos,id_pgt_cad_pos,dat_pgt,dat_vct_tfm,vlr_pgt_tfm,status
0,4822656309,346143461,M,1987,ANAPOLIS,GOIAS,F,90fb53f6-225,41,05082021,NaN,123608.6412,31132431.87,C01,0e3217ed-88e,72854add-8b9,7082019,2019-08-0503:00:00,5980.6140,NaN
1,99535242141,683976061,M,1989,NaN,NaN,F,e4d0eaed-0c6,36,28112021,82864.7388,NaN,NaN,B05,48a5b038-4ed,453f0f88-7e9,11022019,2019-02-2803:00:00,2301.7983,NaN
2,2182440187,273332579,F,1992,NOVOHAMBURGO,RIOGRANDEDOSUL,F,c4ccd097-196,60,11102023,241232.8320,NaN,NaN,B05,dd94b68a-f93,f1cf992a-b7b,13032019,2020-10-1103:00:00,4020.5472,NaN
3,2182440187,273332579,F,1992,NOVOHAMBURGO,RIOGRANDEDOSUL,F,c4ccd097-196,60,11102023,241232.8320,NaN,NaN,B05,914dbfc1-e4c,f4c5862c-b0a,13032019,2022-01-1103:00:00,4020.5472,NaN
4,3348328384,328707139,F,1984,CAMPOGRANDE,MATOGROSSODOSUL,F,e118eeac-2db,48,31012021,236154.7728,NaN,NaN,B05,f4716625-72d,893b8b37-0c4,6092019,2019-09-3003:00:00,4843.3299,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12040,97453879485,676299208,M,1982,JAU,SAOPAULO,F,3743c717-6c9,48,01122021,125680.4640,NaN,NaN,B05,e98e43f2-826,ccdc924b-45b,20032019,2019-04-0103:00:00,2618.3430,NaN
12041,85851406411,108110960,F,1944,CHADEALEGRIA,PERNAMBUCO,F,2cabdbfb-5fc,60,08062020,159329.8620,NaN,NaN,B05,386f7329-08f,9db749df-f47,4042019,2019-04-0803:00:00,2655.4977,NaN
12042,85998454557,108181373,F,1961,NATAL,RIOGRANDEDONORTE,F,4e046719-43e,48,21082021,346128.6816,NaN,NaN,B05,73e4a4bb-9ad,27aa924b-202,9072019,2020-07-2103:00:00,7211.0142,NaN
12043,85874983504,228718939,F,1981,NOVAMUTUM,MATOGROSSO,F,a686dfcc-432,36,10052021,NaN,0.0000,23864076,C01,a8d70cc0-276,d383de9f-6ea,24102018,2018-08-1003:00:00,6661.7418,NaN
12044,96962304357,113722885,F,1965,PALESTINADEGOIAS,GOIAS,F,61eac0b1-22f,84,20112024,NaN,131157.6339,18940765.5,C01,8d45c6c5-8d4,ccb91fda-bec,24122018,2018-12-2002:00:00,2190.9180,NaN

## Agrupando os dados por CPF

In [7]:
df = df_consulta.sort_values(['cpf'])

In [8]:
df.reset_index(level=0, inplace=True)
df_consulta2 = df.drop('index', axis=1)

In [9]:
df_consulta2

,cpf,id,idc_sexo,ano_dat_nascimento,nom_cidade,des_estado,tip_cli,id_opr_cad_pos,qtd_pcl,dat_vct_ult_pcl,vlr_ctrd_fta_tfm,sdo_ddr_tfm,vlr_ctrd,cod_mdl,id_mvt_cad_pos,id_pgt_cad_pos,dat_pgt,dat_vct_tfm,vlr_pgt_tfm,status
0,10007732504,262918781,F,1980,BELOHORIZONTE,MINASGERAIS,F,d4bd170a-519,72,10082022,NaN,7846.1886,32751175.83,C01,3964ae2b-862,b39ded82-970,8072019,2019-07-1003:00:00,4413.9450,NaN
1,10007732504,262918781,F,1980,BELOHORIZONTE,MINASGERAIS,F,d4bd170a-519,72,10082022,NaN,7846.1886,32751175.83,C01,0d480803-68a,41d737c9-64a,11032019,2019-03-1003:00:00,4358.0670,NaN
2,10007732504,262918781,F,1980,BELOHORIZONTE,MINASGERAIS,F,d4bd170a-519,72,10082022,NaN,7846.1886,32751175.83,C01,5029a3e0-a2d,c9967fdd-c97,10052019,2019-05-1003:00:00,4448.5143,NaN
3,10007732504,262918781,F,1980,BELOHORIZONTE,MINASGERAIS,F,d4bd170a-519,72,10082022,NaN,7846.1886,32751175.83,C01,8992c484-be7,e7282cd3-ab0,25012019,2019-02-1002:00:00,4361.3196,NaN
4,10007732504,262918781,F,1980,BELOHORIZONTE,MINASGERAIS,F,d4bd170a-519,72,10082022,NaN,7846.1886,32751175.83,C01,49fde95d-60a,b1c5fe12-be9,7122018,2018-12-1002:00:00,4333.3389,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12040,99771524587,115168357,F,1952,BRASILIA,DISTRITOFEDERAL,F,727da6f5-145,30,16092019,84120.5343,NaN,NaN,B05,9095fefa-bd5,0d75b1d9-b93,18022019,2019-02-1602:00:00,2804.4084,NaN
12041,99771524587,115168357,F,1952,BRASILIA,DISTRITOFEDERAL,F,727da6f5-145,30,16092019,84120.5343,NaN,NaN,B05,e14a378b-ea6,8cfdea11-29b,16052019,2019-05-1603:00:00,2804.4084,NaN
12042,99771524587,115168357,F,1952,BRASILIA,DISTRITOFEDERAL,F,727da6f5-145,30,16092019,84120.5343,NaN,NaN,B05,9d28e02a-77c,5694aadf-749,18032019,2019-03-1603:00:00,2804.4084,NaN
12043,99771524587,115168357,F,1952,BRASILIA,DISTRITOFEDERAL,F,727da6f5-145,30,16092019,84120.5343,NaN,NaN,B05,25542153-74e,70e2ac68-66c,17062019,2019-06-1603:00:00,2804.4084,NaN
12044,99771524587,115168357,F,1952,BRASILIA,DISTRITOFEDERAL,F,727da6f5-145,30,16092019,84120.5343,NaN,NaN,B05,663587f2-748,393fa3cc-cb6,17122018,2018-12-1602:00:00,2804.4084,NaN

## Organizando datas da coluna dat_vct_ult_pcl

In [10]:
for i in df_consulta2.index:
    a = (str(df_consulta2.dat_vct_ult_pcl[i]))
    a = a[0:2] + '/' + a[2:4] + '/' + a[4:8] 
    df_consulta2.dat_vct_ult_pcl[i] = a

c:\users\feh\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

# Organizando datas da coluna dat_pgt

In [11]:
for i in df_consulta2.index:
    a = (str(df_consulta2.dat_pgt[i]))
    if len(a)<8:
        a = '0'+(str(df_consulta2.dat_pgt[i])) 
    a = a[0:2] + '/' + a[2:4] + '/' + a[4:8] 
    df_consulta2.dat_pgt[i] = a

c:\users\feh\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

# Organizando datas da coluna dat_vct_tfm

In [12]:
for i in df_consulta2.index:
    a = (str(df_consulta2.dat_vct_tfm[i]))
    b = a.replace('-', '').replace(':', '')
    b = b[0:-6]
    b = b[6:8] + "/" + b[4:6] + "/" + b[0:4]
    df_consulta2.dat_vct_tfm[i] = b
#dat_vct_list

c:\users\feh\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

# Comparando as colunas

In [13]:
lista = []
for i in df_consulta2.index:
    if df_consulta2.dat_vct_tfm[i] == '//':
        df_consulta2.loc[i, 'status'] = 'APTO'
    else:
        dia_pgt = df_consulta2.dat_pgt[i][0:2]
        mes_pgt = df_consulta2.dat_pgt[i][3:5]
        ano_pgt = df_consulta2.dat_pgt[i][6:11]

        dia_vct = df_consulta2.dat_vct_tfm[i][0:2]
        mes_vct = df_consulta2.dat_vct_tfm[i][3:5]
        ano_vct = df_consulta2.dat_vct_tfm[i][6:11]

        if ano_pgt < ano_vct:
            df_consulta2.loc[i, 'status'] = 'APTO'
        else: 
            if ano_pgt == ano_vct:
                if mes_pgt < mes_vct:
                    df_consulta2.loc[i, 'status'] = 'APTO'
                else:
                    if mes_pgt == mes_vct:
                        if dia_pgt <= dia_vct:
                            df_consulta2.loc[i, 'status'] = 'APTO'
                        else: df_consulta2.loc[i, 'status'] = 'NÃO APTO'
                    else: df_consulta2.loc[i, 'status'] = 'NÃO APTO'
            else: df_consulta2.loc[i, 'status'] = 'NÃO APTO'
                
    if df_consulta2.status[i] == 'NÃO APTO':
        lista.append(df_consulta2.cpf[i])

In [14]:
for i in df_consulta2.index:
    if df_consulta2.cpf[i] in lista:
        df_consulta2.loc[i, 'status'] = 'NÃO APTO'

In [15]:
df_consulta2

,cpf,id,idc_sexo,ano_dat_nascimento,nom_cidade,des_estado,tip_cli,id_opr_cad_pos,qtd_pcl,dat_vct_ult_pcl,vlr_ctrd_fta_tfm,sdo_ddr_tfm,vlr_ctrd,cod_mdl,id_mvt_cad_pos,id_pgt_cad_pos,dat_pgt,dat_vct_tfm,vlr_pgt_tfm,status
0,10007732504,262918781,F,1980,BELOHORIZONTE,MINASGERAIS,F,d4bd170a-519,72,10/08/2022,NaN,7846.1886,32751175.83,C01,3964ae2b-862,b39ded82-970,08/07/2019,10/07/2019,4413.9450,NÃO APTO
1,10007732504,262918781,F,1980,BELOHORIZONTE,MINASGERAIS,F,d4bd170a-519,72,10/08/2022,NaN,7846.1886,32751175.83,C01,0d480803-68a,41d737c9-64a,11/03/2019,10/03/2019,4358.0670,NÃO APTO
2,10007732504,262918781,F,1980,BELOHORIZONTE,MINASGERAIS,F,d4bd170a-519,72,10/08/2022,NaN,7846.1886,32751175.83,C01,5029a3e0-a2d,c9967fdd-c97,10/05/2019,10/05/2019,4448.5143,NÃO APTO
3,10007732504,262918781,F,1980,BELOHORIZONTE,MINASGERAIS,F,d4bd170a-519,72,10/08/2022,NaN,7846.1886,32751175.83,C01,8992c484-be7,e7282cd3-ab0,25/01/2019,10/02/2019,4361.3196,NÃO APTO
4,10007732504,262918781,F,1980,BELOHORIZONTE,MINASGERAIS,F,d4bd170a-519,72,10/08/2022,NaN,7846.1886,32751175.83,C01,49fde95d-60a,b1c5fe12-be9,07/12/2018,10/12/2018,4333.3389,NÃO APTO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12040,99771524587,115168357,F,1952,BRASILIA,DISTRITOFEDERAL,F,727da6f5-145,30,16/09/2019,84120.5343,NaN,NaN,B05,9095fefa-bd5,0d75b1d9-b93,18/02/2019,16/02/2019,2804.4084,NÃO APTO
12041,99771524587,115168357,F,1952,BRASILIA,DISTRITOFEDERAL,F,727da6f5-145,30,16/09/2019,84120.5343,NaN,NaN,B05,e14a378b-ea6,8cfdea11-29b,16/05/2019,16/05/2019,2804.4084,NÃO APTO
12042,99771524587,115168357,F,1952,BRASILIA,DISTRITOFEDERAL,F,727da6f5-145,30,16/09/2019,84120.5343,NaN,NaN,B05,9d28e02a-77c,5694aadf-749,18/03/2019,16/03/2019,2804.4084,NÃO APTO
12043,99771524587,115168357,F,1952,BRASILIA,DISTRITOFEDERAL,F,727da6f5-145,30,16/09/2019,84120.5343,NaN,NaN,B05,25542153-74e,70e2ac68-66c,17/06/2019,16/06/2019,2804.4084,NÃO APTO
12044,99771524587,115168357,F,1952,BRASILIA,DISTRITOFEDERAL,F,727da6f5-145,30,16/09/2019,84120.5343,NaN,NaN,B05,663587f2-748,393fa3cc-cb6,17/12/2018,16/12/2018,2804.4084,NÃO APTO

In [17]:
df_consulta2.to_excel("Tabela única para consulta.xlsx")